---
- name: Install Gitlab runner
  hosts: all
  remote_user: ec2-user
  become: true

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Installing packages
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - yum-utils

    - name: Adding docker repository
      ansible.builtin.yum_repository:
        name: docker
        description: Docker repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Installing Docker
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io