apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-headless
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306