apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
type: Opaque
data:
  mysql-user: {{ .Values.mysql.username }}
  mysql-password: {{ .Values.mysql.password }}
  mysql-database: {{ .Values.mysql.database }}
