version: "3.2"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9300:9300"
    volumes:
      - type: bind
        source: ./inputdata
        target: /csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
